//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AimCecSpect
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Billet
    {
        [Key]
        public int idBillet { get; set; }
        public Nullable<int> idSpectacle { get; set; }
        public Nullable<int> idUtilisateur { get; set; }
        public string statutReservation { get; set; }
    
        public virtual Spectacle Spectacle { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }


        public delegate void ReservationDelegate(int ID_Spectacle, int ID_User);
        public delegate void AnnulationDelegate(int ID_Spectacle, int ID_User);


    }
}
