//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AimCecSpect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spectacle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spectacle()
        {
            this.Billets = new HashSet<Billet>();
        }
    
        public int idSpectacle { get; set; }
        public string titre { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string lieu { get; set; }
        public Nullable<int> nbPlacesDispo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billet> Billets { get; set; }
    }
}
